Wik warning no background
Wikunia/Javis.jl pull request #273
Opened 2020-11-03 10:09 UTC by Wikunia

## PR Checklist

If you are contributing to `Javis.jl`, please make sure you are able to check off each item on this list:

- [ ] Did I update `CHANGELOG.md` with whatever changes/features I added with this PR?
- [x] Did I make sure to only change the part of the file where I introduced a new change/feature?
- [x] Did I cover all corner cases to be close to 100% test coverage (if applicable)?
- [x] Did I properly add Javis dependencies to the `Project.toml` + set an upper bound of the dependency (if applicable)?
- [x] Did I properly add test dependencies to the `test` directory (if applicable)?
- [x] Did I check relevant tutorials that may be affected by changes in this PR?
- [x] Did I clearly articulate why this PR was made the way it was and how it was made?

**Link to relevant issue(s)**
Closes #214 

**How did you address these issues with this PR? What methods did you use?**
The video now saves a range for which a background is defined. The `preprocess_frames!` function then checks whether some frames don't have a background and throws a warning. 
Additionally I've changed some test cases to not throw a warning :smile:

2020-11-03 10:32 UTC, Wikunia commented
I have no idea why format is failing. I've run the `format` command. Maybe you can double check this @TheCedarPrince

2020-11-07 02:56 UTC, TheCedarPrince requested changes
This makes sense - I found one typo and made a minor suggestion on implementation. Only other question that I had is should we seek to identify which Object does not have a background defined?

2020-11-07 02:56 UTC, TheCedarPrince commented on src/Javis.jl
> +        @warn("Some of the frames don't have a background: In this case: ",
"background:" to "background."

2020-11-07 02:56 UTC, TheCedarPrince commented on src/Javis.jl
> +    end
I feel that the warning is a bit verbose:

```
┌ Warning: Some of the frames don't have a background: In this case:
│   setdiff(frames, (CURRENT_VIDEO[1]).background_frames) =
│    1-element Array{Int64,1}:
│     11
└ @ Javis /home/src/Projects/javis/src/Javis.jl:151
```

Perhaps instead we could do this: 

```julia
        @warn("Some of the frames don't have a background: In this case: $(
             setdiff(frames, CURRENT_VIDEO[1].background_frames))")
```

which I think produces the nicer warning:

```
┌ Warning: Some of the frames don't have a background: In this case: [11]
└ @ Javis /home/src/Projects/javis/src/Javis.jl:151
```

2020-11-07 11:11 UTC, Wikunia commented
> Only other question that I had is should we seek to identify which Object does not have a background defined?
I don't think we can.

2020-11-07 17:00 UTC, TheCedarPrince approved these changes

2020-11-07 18:14 UTC, merged