Added `:all` Symbol to Javis
Wikunia/Javis.jl pull request #303
Opened 2020-12-14 20:46 UTC by TheCedarPrince

## PR Checklist

If you are contributing to `Javis.jl`, please make sure you are able to check off each item on this list:

- [x] Did I update `CHANGELOG.md` with whatever changes/features I added with this PR?
- [x] Did I make sure to only change the part of the file where I introduced a new change/feature?
- [x] Did I cover all corner cases to be close to 100% test coverage (if applicable)?
- [x] Did I properly add Javis dependencies to the `Project.toml` + set an upper bound of the dependency (if applicable)?
- [x] Did I properly add test dependencies to the `test` directory (if applicable)?
- [x] Did I check relevant tutorials that may be affected by changes in this PR?
- [x] Did I clearly articulate why this PR was made the way it was and how it was made?

**Link to relevant issue(s)**
Closes #247 

**How did you address these issues with this PR? What methods did you use?**

I added to the Frames.jl and Object.jl file code to allow for finding the maximum of a background frame. I did not add tests as I saw that we have not added tests for the `:same` keyword. Should we add testing? Does the logic make sense here for what I did?

2020-12-15 19:03 UTC, Wikunia requested changes
One minor thing you might want to add and yes please add test cases. I think we actually have some for `:same`. Maybe not unit tests but we use it in some animations.

2020-12-15 19:03 UTC, Wikunia commented on src/structs/Frames.jl
> +        throw(ArgumentError("Currently the only symbols supported for defining frames are `:same` and `:all`."))
we might want to use `join(FRAMES_SYMBOL, ", ", " and ")` or something like that

2021-03-13 12:02 UTC, Wikunia commented
You might wanna have a look @TheCedarPrince 
Do you think this is ready for merging?

2021-03-13 12:22 UTC, Wikunia approved these changes

2021-03-24 02:27 UTC, TheCedarPrince commented
Hey @Wikunia - I tested this out yesterday and all the tests passed on my end! I ran into the ImageIO issue (#315) similar to @flyaflya while testing so I will continue experimenting there. Otherwise, I approve this PR! Feels good to be getting in the groove again! :wink:

2021-03-28 11:01 UTC, merged